# Generated by Django 4.2.28 on 2026-02-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_trip_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_itineraries', to='trips.tripgeneration'),
        ),
    ]
